select * from CONCURSO where rownum =  1 order by IDCONCURSO desc;

SELECT NUMERO FROM NUMERO_APOSTA WHERE NUMERO = 6  OR NUMERO = 7 OR NUMERO = 8 OR NUMERO = 9 OR NUMERO = 10 OR NUMERO = 11;
 
SELECT NUMERO, IDAPOSTA FROM NUMERO_APOSTA;
